"""empty message

Revision ID: 2b32dc56d016
Revises: f4b3d135d753
Create Date: 2022-11-12 06:14:45.915313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b32dc56d016'
down_revision = 'f4b3d135d753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subject', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'subject')
    # ### end Alembic commands ###
