"""empty message

Revision ID: 100685b793eb
Revises: 41cdea7d2c72
Create Date: 2022-11-13 07:49:06.546852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100685b793eb'
down_revision = '41cdea7d2c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subject', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('isadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isadmin')
    op.drop_column('posts', 'subject')
    # ### end Alembic commands ###
