"""empty message

Revision ID: 41cdea7d2c72
Revises: 2b32dc56d016
Create Date: 2022-11-13 07:45:49.528572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cdea7d2c72'
down_revision = '2b32dc56d016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isadmin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isadmin')
    # ### end Alembic commands ###
