"""added Date to Deleted Post Model

Revision ID: 4d32e0ab8b86
Revises: 100685b793eb
Create Date: 2022-11-13 09:41:51.091497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d32e0ab8b86'
down_revision = '100685b793eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_posts', sa.Column('date_added', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'deleted_posts', 'posts', ['date_added'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deleted_posts', type_='foreignkey')
    op.drop_column('deleted_posts', 'date_added')
    # ### end Alembic commands ###
