"""empty message

Revision ID: 62f1bda051ee
Revises: 4d32e0ab8b86
Create Date: 2022-11-13 09:42:58.514455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f1bda051ee'
down_revision = '4d32e0ab8b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_posts', sa.Column('date_added', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'deleted_posts', 'posts', ['date_added'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deleted_posts', type_='foreignkey')
    op.drop_column('deleted_posts', 'date_added')
    # ### end Alembic commands ###
