"""empty message

Revision ID: a46feba13bdc
Revises: bec0276c8329
Create Date: 2022-11-13 09:47:56.204081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46feba13bdc'
down_revision = 'bec0276c8329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_posts', sa.Column('posted_date', sa.String(), nullable=True))
    op.create_foreign_key(None, 'deleted_posts', 'posts', ['posted_date'], ['date_added'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deleted_posts', type_='foreignkey')
    op.drop_column('deleted_posts', 'posted_date')
    # ### end Alembic commands ###
