"""empty message

Revision ID: bec0276c8329
Revises: 62f1bda051ee
Create Date: 2022-11-13 09:44:29.913572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec0276c8329'
down_revision = '62f1bda051ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_posts', sa.Column('date_added', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'deleted_posts', 'posts', ['date_added'], ['date_added'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deleted_posts', type_='foreignkey')
    op.drop_column('deleted_posts', 'date_added')
    # ### end Alembic commands ###
